FIND_PATH(AVRO_INCLUDE_DIR avro.h
    /usr/local/include
    /usr/include
)

SET(AVRO_NAMES avro)
MESSAGE(STATUS "looking for ${AVRO_NAMES}")
FIND_LIBRARY(AVRO_LIBRARY
    NAMES ${AVRO_NAMES}
    PATHS /usr/lib /usr/lib64 /usr/local/lib /usr/local/lib64
)
MESSAGE(STATUS "looking for ${AVRO_LIBRARY}")
IF(AVRO_INCLUDE_DIR AND AVRO_LIBRARY)
    SET(AVRO_FOUND TRUE)
    SET(AVRO_LIBRARIES ${AVRO_LIBRARY})
ELSE(AVRO_INCLUDE_DIR AND AVRO_LIBRARY)
    SET(AVRO_FOUND FALSE)
    SET(AVRO_LIBRARIES)
ENDIF(AVRO_INCLUDE_DIR AND AVRO_LIBRARY)

IF(NOT AVRO_FOUND)
    IF(AVRO_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "AVRO library and headers required.")
    ENDIF(AVRO_FIND_REQUIRED)
ENDIF(NOT AVRO_FOUND)

MARK_AS_ADVANCED(
    AVRO_LIBRARY
    AVRO_INCLUDE_DIR
)