FIND_PATH(HDFS3_INCLUDE_DIR hdfs.h /usr/include/hdfs /usr/local/include/hdfs)

FIND_LIBRARY(HDFS3_LIBRARY NAMES hdfs3 PATH /usr/lib /usr/local/lib /usr/lib64 /usr/local/lib64 /lib /lib64) 

IF (HDFS3_INCLUDE_DIR AND HDFS3_LIBRARY)
    SET(HDFS3_FOUND TRUE)
ENDIF ( HDFS3_INCLUDE_DIR AND HDFS3_LIBRARY)

IF (HDFS3_FOUND)
    IF (NOT HDFS3_FIND_QUIETLY)
	MESSAGE(STATUS "Found HDFS3: ${HDFS3_LIBRARY}")
    ENDIF (NOT  HDFS3_FIND_QUIETLY)
ELSE(HDFS3_FOUND)
  IF (HDFS3_FIND_REQUIRED)
	  IF(NOT HDFS3_INCLUDE_DIR)
	    MESSAGE(FATAL_ERROR "Could not find LibHDFS3 header file!")
	  ENDIF(NOT HDFS3_INCLUDE_DIR)

	  IF(NOT HDFS3_LIBRARY)
	    MESSAGE(FATAL_ERROR "Could not find LibHDFS3 library file!")
	  ENDIF(NOT HDFS3_LIBRARY)
  ENDIF (HDFS3_FIND_REQUIRED)
ENDIF (HDFS3_FOUND)