FIND_PATH(RDKAFKA_INCLUDE_DIR rdkafka.h
    /usr/local/include/librdkafka
    /usr/local/include
    /usr/include/librdkafka
    /usr/include
)

SET(RDKAFKA_NAMES rdkafka)
FIND_LIBRARY(RDKAFKA_LIBRARY
    NAMES ${RDKAFKA_NAMES}
    PATHS /usr/lib /usr/local/lib
)

IF(RDKAFKA_INCLUDE_DIR AND RDKAFKA_LIBRARY)
    SET(RDKAFKA_FOUND TRUE)
    SET(RDKAFKA_LIBRARIES ${RDKAFKA_LIBRARY})
ELSE(RDKAFKA_INCLUDE_DIR AND RDKAFKA_LIBRARY)
    SET(RDKAFKA_FOUND FALSE)
    SET(RDKAFKA_LIBRARIES)
ENDIF(RDKAFKA_INCLUDE_DIR AND RDKAFKA_LIBRARY)

IF(NOT RDKAFKA_FOUND)
    IF(RDKAFKA_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "rdkafka library and headers required.")
    ENDIF(RDKAFKA_FIND_REQUIRED)
ENDIF(NOT RDKAFKA_FOUND)

MARK_AS_ADVANCED(
    RDKAFKA_LIBRARY
    RDKAFKA_INCLUDE_DIR
)