FIND_PATH(CONFIG_INCLUDE_DIRS libconfig.h /usr/include /usr/local/include)

FIND_LIBRARY(CONFIG_LIBRARIES NAMES config PATH /usr/lib /usr/lib64 /usr/local/lib /usr/local/lib64) 

IF (CONFIG_INCLUDE_DIRS AND CONFIG_LIBRARIES)
    SET(CONFIG_FOUND TRUE)
ENDIF ( CONFIG_INCLUDE_DIRS AND CONFIG_LIBRARIES)

IF (NOT CONFIG_FOUND)
    IF (CONFIG_FIND_REQUIRED)
		IF (NOT CONFIG_INCLUDE_DIRS)
			MESSAGE(FATAL_ERROR "Could not find LibConfig header file!")
		ENDIF (NOT CONFIG_INCLUDE_DIRS)

		IF (NOT CONFIG_LIBRARIES)
			MESSAGE(FATAL_ERROR "Could not find LibConfig library file!")
		ENDIF (NOT CONFIG_LIBRARIES)
    ENDIF (CONFIG_FIND_REQUIRED)
ENDIF ()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(CONFIG DEFAULT_MSG CONFIG_LIBRARIES CONFIG_INCLUDE_DIRS)

mark_as_advanced(CONFIG_INCLUDE_DIRS CONFIG_LIBRARIES)