FIND_PATH(AVRO_INCLUDE_DIRS avro.h
    /usr/local/include
    /usr/include
)

SET(AVRO_NAMES avro)

FIND_LIBRARY(AVRO_LIBRARY
    NAMES ${AVRO_NAMES}
    PATHS /usr/lib /usr/lib64 /usr/local/lib /usr/local/lib64
)

IF(AVRO_INCLUDE_DIRS AND AVRO_LIBRARY)
    SET(AVRO_FOUND TRUE)
    SET(AVRO_LIBRARIES ${AVRO_LIBRARY})
ELSE(AVRO_INCLUDE_DIRS AND AVRO_LIBRARY)
    SET(AVRO_FOUND FALSE)
    SET(AVRO_LIBRARIES)
ENDIF(AVRO_INCLUDE_DIRS AND AVRO_LIBRARY)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(AVRO DEFAULT_MSG AVRO_LIBRARIES AVRO_INCLUDE_DIRS)

mark_as_advanced(
    AVRO_LIBRARIES
    AVRO_INCLUDE_DIRS
)