FIND_PATH(SERDES_INCLUDE_DIR
    NAMES "serdes.h"
	PATHS /usr/include/libserdes /usr/include /usr/local/include/libserdes /usr/local/include
)
MESSAGE(STATUS "SERDES_INCLUDE_DIR = ${SERDES_INCLUDE_DIR}")

SET(SERDES_NAMES serdes)
FIND_LIBRARY(SERDES_LIBRARY
	NAMES ${SERDES_NAMES}
	PATHS /usr/lib /usr/lib64 /usr/local/lib /usr/local/lib64
)
MESSAGE(STATUS "SERDES_LIBRARY = ${SERDES_LIBRARY}")

IF(SERDES_INCLUDE_DIR AND SERDES_LIBRARY)
	SET(SERDES_FOUND TRUE)
	SET(SERDES_LIBRARIES ${SERDES_LIBRARY})
ELSE(SERDES_INCLUDE_DIR AND SERDES_LIBRARY)
	SET(SERDES_FOUND FALSE)
	SET(SERDES_LIBRARIES)
ENDIF(SERDES_INCLUDE_DIR AND SERDES_LIBRARY)

IF(NOT SERDES_FOUND)
	IF(SERDES_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "SERDES library and headers required.")
	ENDIF(SERDES_FIND_REQUIRED)
ENDIF(NOT SERDES_FOUND)

MARK_AS_ADVANCED(
	SERDES_LIBRARY
	SERDES_INCLUDE_DIR
)