FIND_PATH(SERDES_INCLUDE_DIRS
    NAMES "serdes.h"
	PATHS /usr/include/libserdes /usr/include /usr/local/include/libserdes /usr/local/include
)
MESSAGE(STATUS "SERDES_INCLUDE_DIRS = ${SERDES_INCLUDE_DIRS}")

SET(SERDES_NAMES serdes)
FIND_LIBRARY(SERDES_LIBRARY
	NAMES ${SERDES_NAMES}
	PATHS /usr/lib /usr/lib64 /usr/local/lib /usr/local/lib64
)

IF(SERDES_INCLUDE_DIRS AND SERDES_LIBRARY)
	SET(SERDES_FOUND TRUE)
	SET(SERDES_LIBRARIES ${SERDES_LIBRARY})
ELSE(SERDES_INCLUDE_DIRS AND SERDES_LIBRARY)
	SET(SERDES_FOUND FALSE)
	SET(SERDES_LIBRARIES)
ENDIF(SERDES_INCLUDE_DIRS AND SERDES_LIBRARY)

IF(NOT SERDES_FOUND)
	IF(SERDES_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "SERDES library and headers required.")
	ENDIF(SERDES_FIND_REQUIRED)
ENDIF(NOT SERDES_FOUND)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SERDES DEFAULT_MSG SERDES_LIBRARIES SERDES_INCLUDE_DIRS)

MARK_AS_ADVANCED(
	SERDES_LIBRARIES
	SERDES_INCLUDE_DIRS
)